version: 2.1

jobs:
  build-test-push:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: TAG
          command: echo '$CIRCLE_TAG'
      - run:
          name: Generate-Image
          command: docker build . -t lucasalbertoni/countries
      - run:
          name: Login-Dockerhub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push-Dockerhub
          command: docker push lucasalbertoni/countries
      - run:
          name: Logout-Dockerhub
          command: docker logout
      - run:
          name: Remove-File
          command: rm /home/circleci/.docker/config.json

workflows:
  execute-process:
    jobs:
      - build-test-push
